public class App {
    public static void main(String[] args) throws Exception {
        Uni5Exe01.main(args);
        Uni5Exe02.main(args);
        Uni5Exe03.main(args);
        Uni5Exe04.main(args);
        Uni5Exe05.main(args);
        Uni5Exe06.main(args);
        Uni5Exe07.main(args);
        Uni5Exe08.main(args);
        Uni5Exe09.main(args);
        Uni5Exe10.main(args);
        Uni5Exe11.main(args);
        Uni5Exe12.main(args);
        Uni5Exe13.main(args);
        Uni5Exe14.main(args);
        Uni5Exe15.main(args);
        Uni5Exe16.main(args);
        Uni5Exe17.main(args);
        Uni5Exe18.main(args);
        Uni5Exe19.main(args);
        Uni5Exe20.main(args);
        Uni5Exe21.main(args);
        Uni5Exe22.main(args);
        Uni5Exe23.main(args);
        Uni5Exe24.main(args);
        Uni5Exe25.main(args);
    }
}
